### PR TITLE
Cannibalism!

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Allows people to butcher human limbs with sharp objects to get human meat, bones and sinew. Yum!

Note: I am not a coder, this code is probably 10x bigger than it needs to be. Don't hate me.

## Why It's Good For The Game

Cannibalism is fun for RP and this fleshes it out a little more. Gone are the days of needing to find a gibber or eat organs!

## Pre-Merge Checklist
- [✓] Your Pull Request contains no breaking changes
- [✓] You tested your changes locally, and they work.
- [✓] There are no new Runtimes that appear.
- [✓] You documented all of your changes.

## Changelog
:cl:
add: Made it so you can butcher all 4 human limbs to get meat, sinew and bone.
/:cl:

### CODE REVIEW

**Comment by Jaaackx** [comment]
a4dQRVmnQw

This was before I added the sinew, but you get the idea.

**Comment by Jaaackx** [comment]
I have no idea what this Linters thing is, halp.

**Comment by printer16** [comment]
> I have no idea what this Linters thing is, halp.

You'll need an empty space at the end of the file.

**Comment by Jaaackx** [comment]
WOO! I think this is good to go. @printer16 Thanks for the help.

**Comment by Jaaackx** [comment]
Added gibs for extra grossness. NOW it's done.

**Comment by Jaaackx** [comment]
I lied, gibs didn't work, now they do.

**Comment by Jaaackx** [comment]
Okay, I had to make like 3 tweaks but it is 100% ready to go now. AAAAAAAAAAAAAGH. Assuming the checks pass. I am bad coder.

**Pull request merged**
