### PR TITLE
Den Rework Update (Ready, chem addictions removed)

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Adds fog effect, doesn't add it to the map.
Adds Khan and Den chem vendors, Khan lower price.
Adds addiction quirks, not yet balanced, waiting for feedback. -- REMOVED DUE TO RUNTIME ERRORS
Increases addiction threshold of nicotine so it's not so annoying.
Adds a fence vendor to sell BoS gear to, doesn't add it to the map. Could do with admin spawn for testing how it functions in round.
Removes fixer from several places to make addictions more meaningful.

## Why It's Good For The Game

Literally just adding stuff.

## Pre-Merge Checklist
- [yep] Your Pull Request contains no breaking changes
- [yep] You tested your changes locally, and they work.
- [yep] There are no new Runtimes that appear.
- [yep] You documented all of your changes.

## Changelog
:cl:
add: fog effect
add: chem vendors
add: addiction quirks
add: fence vendor for BoS
del: fixer from a bunch of places
tweak: nicotine addiction
/:cl:

### CODE REVIEW

**Comment by Jaaackx** [comment]
okay checks SHOULD pass now

**Comment by hecksadecimal** [comment]
Alright. I'll add this to the testmerges.

**Comment by hecksadecimal** [comment]
Here's the runtimes with sensitive data removed.
```
Loading Yuma...
Loaded Wasteland in 10.3s!
Loaded Virtual Reality in 3.7s!
Ruin loader finished with 0 left to spend.
## WARNING: No /obj/docking_port/mobile/arrivals placed on the map! in code/controllers/subsystem/shuttle.dm at line 80 src: Shuttle usr: .
Loaded 0 engraved messages on map Yuma
Initializations complete within 129.1 seconds!
Game start took 0s
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Med-X Addict (/datum/quirk/junkie/medx)
  call stack:
  Med-X Addict (/datum/quirk/junkie/medx): announce drugs()
  Med-X Addict (/datum/quirk/junkie/medx): on spawn()
  Med-X Addict (/datum/quirk/junkie/medx): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/medx (/datum/quirk/junkie/medx), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Mentats Addict (/datum/quirk/junkie/mentats)
  call stack:
  Mentats Addict (/datum/quirk/junkie/mentats): announce drugs()
  Mentats Addict (/datum/quirk/junkie/mentats): on spawn()
  Mentats Addict (/datum/quirk/junkie/mentats): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/mentats (/datum/quirk/junkie/mentats), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Buffout Addict (/datum/quirk/junkie/buffout)
  call stack:
  Buffout Addict (/datum/quirk/junkie/buffout): announce drugs()
  Buffout Addict (/datum/quirk/junkie/buffout): on spawn()
  Buffout Addict (/datum/quirk/junkie/buffout): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/buffout (/datum/quirk/junkie/buffout), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Turbo Addict (/datum/quirk/junkie/turbo)
  call stack:
  Turbo Addict (/datum/quirk/junkie/turbo): announce drugs()
  Turbo Addict (/datum/quirk/junkie/turbo): on spawn()
  Turbo Addict (/datum/quirk/junkie/turbo): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/turbo (/datum/quirk/junkie/turbo), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Psycho Addict (/datum/quirk/junkie/psycho)
  call stack:
  Psycho Addict (/datum/quirk/junkie/psycho): announce drugs()
  Psycho Addict (/datum/quirk/junkie/psycho): on spawn()
  Psycho Addict (/datum/quirk/junkie/psycho): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/psycho (/datum/quirk/junkie/psycho), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,478: Cannot read null.type
  proc name: on spawn (/datum/quirk/junkie/on_spawn)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on spawn()
  Junkie (/datum/quirk/junkie): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie (/datum/quirk/junkie), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:32:41] Runtime in negative.dm,510: Cannot read null.name
  proc name: announce drugs (/datum/quirk/junkie/proc/announce_drugs)
  src: Jet Addict (/datum/quirk/junkie/jet)
  call stack:
  Jet Addict (/datum/quirk/junkie/jet): announce drugs()
  Jet Addict (/datum/quirk/junkie/jet): on spawn()
  Jet Addict (/datum/quirk/junkie/jet): New( (/mob/living/carbon/human), 1)
   (/mob/living/carbon/human): add quirk(/datum/quirk/junkie/jet (/datum/quirk/junkie/jet), 1)
  Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), Silver_Legion (/client), 1, 0, /datum/job/wasteland/f13raider (/datum/job/wasteland/f13raider), 0, null)
  Silver_Legion (/mob/dead/new_player): AttemptLateSpawn("Outlaw")
  Silver_Legion (/mob/dead/new_player): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
  Silver_Legion (/client): Topic("src=\[mob_1403];SelectedJob=Ou...", /list (/list), Silver_Legion (/mob/dead/new_player))
[14:33:01] Runtime in asset_transport.dm,87: Invalid argument: client: ``
  proc name: send assets (/datum/asset_transport/proc/send_assets)
  src: Simple browse_rsc asset transp... (/datum/asset_transport)
  call stack:
  Simple browse_rsc asset transp... (/datum/asset_transport): send assets(null, /list (/list))
  /datum/asset/simple/lobby (/datum/asset/simple/lobby): send(null)
  ConstantineIII (/mob/dead/new_player): new player panel()
  ConstantineIII (/mob/dead/new_player): make me an observer()
  ConstantineIII (/mob/dead/new_player): Topic("src=\[mob_1281];ready=2", /list (/list))
  ConstantineIII (/client): Topic("src=\[mob_1281];ready=2", /list (/list), ConstantineIII (/mob/dead/new_player))
  ConstantineIII (/client): Topic("src=\[mob_1281];ready=2", /list (/list), ConstantineIII (/mob/dead/new_player))
[14:34:32] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:33] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:34] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:35] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:37] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:38] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:39] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:40] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:41] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:42] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:43] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  src: Junkie (/datum/quirk/junkie)
  call stack:
  Junkie (/datum/quirk/junkie): on process()
  Junkie (/datum/quirk/junkie): process(10)
  Quirks (/datum/controller/subsystem/processing/quirks): fire(0)
  Quirks (/datum/controller/subsystem/processing/quirks): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[14:34:44] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:45] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:46] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:47] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:49] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:50] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:51] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:53] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:54] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:55] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:56] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:57] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:34:59] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:00] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:02] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:03] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:04] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:05] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:07] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:08] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:09] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:10] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:11] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:13] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:14] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:15] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:16] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:17] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:18] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:19] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:21] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:22] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:23] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:24] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:25] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:26] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:27] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:28] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:29] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
[14:35:31] Runtime in negative.dm,522: Cannot modify null.addiction_stage.
  proc name: on process (/datum/quirk/junkie/on_process)
  (This error will now be silenced for 10 minutes)
```

**Comment by Jaaackx** [comment]
chem addiction quirks have been removed for the time being as there is other stuff I want merged from this PR, will open a separate one for those quirks, this is good to go as long as checks pass

**Pull request closed without merging**
