### PR TITLE
Runtimes

### PR DESCRIPTION
**Pull request by buffyuwu**
more fixes

we will want to merge this with https://github.com/FortunaSS13/Fortuna/pull/267 and https://github.com/FortunaSS13/Fortuna/pull/256 for consistency

ThyBaron edit:
----------------
This PR includes messages per staff request, and a configuration manual for the virtual reality machinery in-game. Furthermore, this takes a whack at the lighting and such!

### CODE REVIEW

**Review by hecksadecimal — CHANGES_REQUESTED** [review]
Use the PR template.

**Review by ThyBaron — APPROVED** [review]
These go by expectation!

**Comment by hecksadecimal** [comment]
Not a fan of our standards being arbitrarily ignored, the PR template is there for a reason and it sets a bad precedent to just let PRs slip that don't use it.

But alright then.

**Review by hecksadecimal — APPROVED** [review]

**Comment by ThyBaron** [comment]
> Not a fan of our standards being arbitrarily ignored, the PR template is there for a reason and it sets a bad precedent to just let PRs slip that don't use it.
> 
> But alright then.

These developments undertaken are for optimization from the looks, and following examination. HOWEVER! The unannounced additions are, indeed, an issue. We do desperately need optimization further to this code, and sometimes that bureaucratic red tape can go snipped away! (Not for each and every instance though!)

**Comment by Looreydev** [comment]
> more fixes
> 
> we will want to merge this with #267 and #256 for consistency
> 
> ## ThyBaron edit:
> This PR includes messages per staff request, and a configuration manual for the virtual reality machinery in-game. Furthermore, this takes a whack at the lighting and such!

For future reference: Use the PR Template. It's really not a witchcraft to fill it out in a few seconds, even if it's not a supermassive thing it's a Standard and I will just close PR's in the future.

**Pull request merged**
