### PR TITLE
Removes Tinkering

### PR DESCRIPTION
**Pull request by BadIsMyUsername**
## About The Pull Request
Removes all traces I could find of tinkering, including:
- The master gunsmith trait and skill granters for said trait
- Large swathes of tinkering and inventing code
- The scavenging and tinkering crafting tab
- Two variables attached to every single /obj/item that was only checked for on guns (I am crying).
- Other nonsense
So far crafting components and salvage have not been touched.

## Why It's Good For The Game
Not only was this system poorly coded (I started crying while looking at the code during the removal), it was also very bad in practice, relying on RNG to make overpowered weapons. Widely requested removal by many moderators and other members of the Fallout 13 community. 

## Changelog
:cl:
del: Removed all traces of tinkering I could find
/:cl:

### CODE REVIEW

**Comment by panzer1944** [comment]
hi. If your removing tinkering, but not salvaging as a whole or the armour repair system or anything, please do leave in the invention crafting, PA repair crafting, armour repair crafting - having things become unrepairable because you decided to obliterate tinkering and only a part of salvaging with it would be bad.

**Comment by BadIsMyUsername** [comment]
> hi. If your removing tinkering, but not salvaging as a whole or the armour repair system or anything, please do leave in the invention crafting, PA repair crafting, armour repair crafting - having things become unrepairable because you decided to obliterate tinkering and only a part of salvaging with it would be bad.

Durability will be removed in a future PR, inventing was poorly coded and also sort of lame (if you had the tinkering trait, your invention success probabilty chance got WORSE instead of better). I have no plans to alter salvaging in anyway at this moment.

**Comment by panzer1944** [comment]
> > hi. If your removing tinkering, but not salvaging as a whole or the armour repair system or anything, please do leave in the invention crafting, PA repair crafting, armour repair crafting - having things become unrepairable because you decided to obliterate tinkering and only a part of salvaging with it would be bad.
> 
> Durability will be removed in a future PR, inventing was poorly coded and also sort of lame (if you had the tinkering trait, your invention success probabilty chance got WORSE instead of better). I have no plans to alter salvaging in anyway at this moment.
you see though, you removed almost all of this 
image
which is bad, since you only needed to remove the tinkering currently
removing pin-removal, armour repair while the system is still in and cutting things into cloth is bad

**Comment by BadIsMyUsername** [comment]
Alright, let me make a commit to restore that then.

**Review by Looreydev — CHANGES_REQUESTED** [review]
There's more traces of tinkering in code.

For example:
[gun.dm: Line 250](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/projectiles/gun.dm#L250)
[_head.dm: Line 14](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/clothing/head/_head.dm#L14)
[_suits.dm: Line 19](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/clothing/suits/_suits.dm#L19)

Although those are commented out, it'd still be nice to have every trace properly removed.

**Comment by BadIsMyUsername** [comment]
> There's more traces of tinkering in code, probably even more than the 3 I found in a very quick search.
> 
> For example:
> [gun.dm: Line 250](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/projectiles/gun.dm#L250)
> [_head.dm: Line 14](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/clothing/head/_head.dm#L14)
> [_suits.dm: Line 19](https://github.com/FortunaSS13/Fortuna/blob/ffb7f7537f46dc3d40c56a10774084a1814b085d/code/modules/clothing/suits/_suits.dm#L19)
> 
> Although those are commented out, it'd still be nice to have every trace properly removed.

Done! I looked for everything else with 'tinker' in it via VSCodium, couldn't find anything more relating to F13 code.

**Comment by Looreydev** [comment]
@BadIsMyUsername was this tested by you?

**Review by Looreydev — APPROVED** [review]

**Comment by BadIsMyUsername** [comment]
> @BadIsMyUsername was this tested by you (that everything is properly gone)?

Do you mean like a local server test? If so, yeah.

**Comment by Looreydev** [comment]
Maybe we'll implement a system for customizing weapons that is not bad by design at some point, no guarantees.

**Comment by VEN0M5** [comment]
I haven't looked through the changes in this PR, but I assumed that the part where you convert salvage PA to powered is also removed? As the process involves using the salvaged PA on the tinker item.

**Pull request merged**
