### PR TITLE
Huge bug fixes, fixes bug for APC blackout (Requested by Baron)

### PR DESCRIPTION
**Pull request by mishulinya**
## About The Pull Request

- Smelling salts fix

- Economy fix (Maintenance loot fix/Money Rebalance)

- Turbo fix

- Combat Stamina Fix (fixes combat stamina stupidity and such)

- Fixes surrender emote and adds sound for it

- Fixes APC blackout described by pilotbland

Credits: - MarinaGryphon (Smelling Salts)
         - gurking + judgex (money rebalance)
         - panzer1944 (turbo fix)
         - Lamasmaster (Combat Mode fix THANK GOD + Surrender fix)

## Why It's Good For The Game

Baron requested these changes and wanted to port them to the server. It fixes combat mode with it's stupid ass stamina, fixes turbo, fixes the economy a bit, fixes surrender emote and adds a sound for it, fixes smelling salts to work on the chest and stops the retarded combat stamina draining.

## Pre-Merge Checklist
- [X] Your Pull Request contains no breaking changes
- [X] You tested your changes locally, and they work.
- [X] There are no new Runtimes that appear.
- [X] You documented all of your changes.

## Changelog
:cl:
add: bug fixes
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: The economy.
fix: Smelling salts, combat mode etc
soundadd: surrender1.ogg
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: lots of it
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by mishulinya** [comment]
Ok, let me check what's wrong with this.

**Comment by mishulinya** [comment]
Fucking BYOND code.

**Comment by mishulinya** [comment]
Ok i managed to reduce the errors to 5.

**Review by printer16 — CHANGES_REQUESTED** [review]
Did you mean to place autolathe_designs.dm and autolathe_designs_electronics.dm in the root folder?

Also power_armor.dm can probably just be deleted entirely since it's unused.

**Comment by mishulinya** [comment]
Yes, i meant to add the autolathe designs and such to fix the APC bug that PilotBland mentioned, for the PA.dm i don’t know why that’s there since GitHub is stupid because that’s already in my deflection PR.

**Comment by mishulinya** [comment]
I’ll just fix this stupid piece of junk once i come back from work.

**Comment by BadAtThisGame302** [comment]
The dev of the PR left

**Pull request closed without merging**
