### PR TITLE
Removes closet looking for ghosts

### PR DESCRIPTION
**Pull request by printer16**
## About The Pull Request

Disallows ghosts from viewing what's in closets unless they are an admin.

## Why It's Good For The Game

This helps combat meta.

## Pre-Merge Checklist
- [X] Your Pull Request contains no breaking changes
- [X] You tested your changes locally, and they work.
- [X] There are no new Runtimes that appear.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by hecksadecimal** [comment]
I like this in theory.
In practice though, ghosted admins could still find this functionality important.
Thoughts?

**Comment by printer16** [comment]
> I like this in theory.
> In practice though, ghosted admins could still find this functionality important.
> Thoughts?

I didn't think about that! I will enable the feature for admins.

**Comment by zuliouse** [comment]
Note that admins can use View Variables to check the contents of any container, including closets, so it isn't essential to enable it.

**Comment by hecksadecimal** [comment]
> 
> 
> Note that admins can use View Variables to check the contents of any container, including closets, so it isn't essential to enable it.

Not essential, but it is more convenient than using VV.

**Review by Looreydev — COMMENTED** [review]
Makes it more convenient, I guess. Not like the VV-Panel is hard to use either. ¯\_(ツ)_/¯

**Comment by printer16** [comment]
It has been updated to allow admins to still use the feature, by the way.

**Pull request merged**
