### PR TITLE
multiple rifles buff

### PR DESCRIPTION
**Pull request by carbous**
## About The Pull Request
buffing some relatively weak rifles, namely the service rifle, marksman carbine and the range master. changes are as follow, the service rifle now does 37 damages with fmj, the marksman's damages has been increased by 6 but its fire rate lightly reduced
and the rangemaster has now +7 damages to match its tier.

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
balance: Buff damage for rifles
/:cl:

### CODE REVIEW

**Comment by Looreydev** [comment]
Keep in mind that there's a [Pull Request Template](https://github.com/FortunaSS13/Fortuna/blob/master/.github/PULL_REQUEST_TEMPLATE.md) that's there to be used to make lives a bit easier and not overwritten by something else.

**Comment by Looreydev** [comment]
> Keep in mind that there's a [Pull Request Template](https://github.com/FortunaSS13/Fortuna/blob/master/.github/PULL_REQUEST_TEMPLATE.md) that's there to be used to make lives a bit easier and not overwritten by something else.

For the future at least.

**Review by hecksadecimal — CHANGES_REQUESTED** [review]
I've added the PR template for you. At the bare minimum, please go through the pre-merge checklist and make sure everything's alright.

**Comment by carbous** [comment]
> I've added the PR template for you. At the bare minimum, please go through the pre-merge checklist and make sure everything's alright.

**Comment by carbous** [comment]
alright, not very used to github in general, but its done

**Pull request closed without merging**
