### PR TITLE
disables mutation toxins

### PR DESCRIPTION
**Pull request by zuliouse**
## About The Pull Request

Title.

## Why It's Good For The Game

Mutation toxins bad, shouldn't be accessible, so let's disable them.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
del: Disabled mutation toxins
/:cl:

### CODE REVIEW

**Comment by ThyBaron** [comment]
As much as I'd like to, we should look to formulating an alternative before we do so.

**Comment by zuliouse** [comment]
> As much as I'd like to, we should look to formulating an alternative before we do so.

An alternative to what? The only reason these are accessible is through a seed that has a small chance to contain any reagent in the game. I don't think we really need an alternative method for people to turn themselves into catgirls or shadow demons (two examples of what these mutation toxins do).

**Comment by AdamElTablawy** [comment]
> As much as I'd like to, we should look to formulating an alternative before we do so.

No alternative is necessary.

They're just derilect content that turn you into slimes.

**Review by buffyuwu — APPROVED** [review]
slimes bad

**Pull request merged**
