### PR TITLE
The big VR Update

### PR DESCRIPTION
**Pull request by hecksadecimal**
## About The Pull Request
My previous VR stuff was just a quick fix to get rid of the enclave bunker. Now I'm back again with a whole batch of changes to the VR map and functionality related to it. )

Brotherhood has been given a new VR Scenario. It's a copy of the Casino. They also have an Arena they can spar together in. This is just copied from the centcom map and modified to work under this use case.
image
image

The Followers, Brotherhood, and Den / Khans each have access to a crafting recipe to turn a standard vr sleeper board into one specifically for their faction. This has a few benefits, as the different VR areas are tailored to specific purposes. For instance, the Den's VR sleepers have a special property which allows their VR avatars to transport over to the Brotherhood training sims, and their avatars are ignored by the mobs there. Additionally, a faction board can be reset into a standard board with another crafting recipe. 

And finally, there's public VR sleepers and an area for them as well, but these sleepers must be constructed after their boards are found. I've placed two sleeper boards deep into the vault, and the brotherhood is capable of printing more with R&D. This will let the general public have some TDM fun in the arena.

Brotherhood VR Area
image

Den VR Area
image

Followers VR Area
image

Public VR Area
image

## Why It's Good For The Game
VR deserved more love than what I gave it the first time around. Now most other factions can get in on the VR fun too.

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl: 0xEFF
add: VR area for Followers
add: VR area for Den
add: Casino VR Scenario for Brotherhood
add: Public Arena VR Scenario
add: Private Arena VR Scenario for Brotherhood
add: Ability for Den / Khans to interfere with the Brotherhood's VR training sims
/:cl:

### CODE REVIEW

**Comment by zuliouse** [comment]
Den Clinic has a space tile under the door to the VR room. https://imgur.com/a/w4E0t1n

**Comment by zuliouse** [comment]
It seems that people who enter VR are able to use Brotherhood comms, despite not being in the Brotherhood. Further testing required.

**Comment by hecksadecimal** [comment]
> 
> 
> It seems that people who enter VR are able to use Brotherhood comms, despite not being in the Brotherhood. Further testing required.

Can't replicate this. Are you sure it isn't just people taking brotherhood headsets off dead VR bodies?

**Comment by hecksadecimal** [comment]
Well, I made it so those faction radios on VR bodies can't be removed.
image

**Comment by hecksadecimal** [comment]
Depends on #122, do not merge until that gets in.

**Pull request merged**
