### PR TITLE
Removes numerous NCR slots, buffs the sergeant role considerably. Requested PR.

### PR DESCRIPTION
**Pull request by ghost**
0 Captain

1 LT (marksman carbine)

2 Sgt (r91, trench shotgun, or sniper rifle)

2 Corporal (r82 or scout carbine)

4 Trooper (same as always)

5 off duties that don't matter

1 combat engineer (the three usual loadouts but the service rifle is replaced with the r82)

1 combat medic

1 medical officer that does not participate in combat

2 MPs that do not participate in combat (cattleprod instead of telebaton)

0 vet ranger

0 heavy trooper

0 logistics officer

the r82 unironically kind of sucks so the biggest balance change is the sgt honestly

The NCR no longer has a surplus of medical roles etc due to the loss of rear ech.

Various descriptions have been modified to reflect new situations, such as the loss of the vet ranger and the captain, an order for MPs *not* to leave the base (because they shouldn't be).

The NCR has lost 2 of its most powerful sets of armor with the loss of the HT and the veteran ranger, both being extremely powerful otherwise.

Everyone in the NCR can recolor salvaged PA now since apparently they couldn't before and everyone assumed they could, so i'll assume this was just some kind of weird change. It's just spraypainting it, anyway.

The NCR's combat engineer can now craft some weapons that they couldn't before to compensate for the loss of the LO who could make rangemasters, etc-these weapons are things the NCR already spawns with. Specifically, they can craft R82s and the entrenching tools on top of what they could make before.

## About The Pull Request

i was asked to

## Why It's Good For The Game

i was asked to

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Buffed the NCR's guns a little bit. A lot bit in the case of the sergeant.
add: Anyone in the NCR can repaint salvaged PA now.
add: Off-duty is now a role in the NCR.
del: Removed numerous roles in the NCR to shrink the faction some.
del: Removed veteran ranger. Riot now.
/:cl:

### CODE REVIEW

**Comment by zuliouse** [comment]
NB: Do not merge until concurrent changes are ready.

**Comment by AdamElTablawy** [comment]
tempclose

**Comment by ValoTheValo** [comment]
i dont even play f13 anymore and i can tell this is a bad idea

**Comment by AdamElTablawy** [comment]
> 

i got asked to reduce the slots to fit the new NCR map and the same with the legion because we have less playercount, and that heavy trooper was lore violating

don't look at me

**Comment by buffyuwu** [comment]
ehhhh @zuliouse didn’t we just implement new ranger sprites

**Comment by zuliouse** [comment]
> ehhhh @zuliouse didn’t we just implement new ranger sprites
> 
> who requested this?

I asked for it a century ago back when we decided factions were too bloated and slots needed to lower. Do people still play Veteran Ranger? If so we can probably find a way to make it stay. I don't really care what happens to the role, Vet Rangers are kind of useless either way.

**Comment by carbous** [comment]
there is a couple people who main vet ranger yes, and their quality has improved, i kinda like some aspect of this pr, like giving some more power to sergeant but well, NCR lose all means to make the r84 i think and some of the loadouts aren't very good, like the sniper rifle for the sergeant, scout carbine being worst than the service rifle and useless as a sniper too.

**Pull request closed without merging**
