### PR TITLE
Move Enclave bunker to VR Z-level

### PR DESCRIPTION
**Pull request by hecksadecimal**
## About The Pull Request
We've been wanting to remove the Enclave bunker for a while now, and this represents a good opportunity for it. I've added a VR z-level for the BoS to use for training exercises, and in the future I'll be adding a section in it for the Followers to train their own personnel as well. 

The BoS now have access to the Enclave bunker as a VR destination, and the space that this dungeon used to occupy on the underground map has been replaced with some rich ore pockets. Currently the VR armoury is just a copy of the BoS armoury room with a lot of additional equipment to help instructors tailor the exercise. If someone who's actually good at mapping wanted to take a shot at this, they're more then welcome to.

====IMPORTANT NOTE====
This PR requires server config changes. 
In game_options.txt uncomment `ROUNDSTART_VR`
In vr_config.txt add `_maps/RandomZLevels/VR/yuma_VR.dmm`

image
image
image
image

## Why It's Good For The Game
The Enclave bunker needed to go, mainly due to it being a constant source of metarushing due to the incredible loot that it contained. BoS VR training was also desired for a while. 

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl: 0xEFF
add: Added VR sleepers and a VR z-level, currently accessible by the BoS
del: Removed Enclave bunker from public access
/:cl:

### CODE REVIEW

**Comment by Zembaflemba** [comment]
Instead of straight up removing it, maybe swap the loot in the Enclave Bunker with the loot from the Casino, since the Casino is many times harder.

**Comment by hecksadecimal** [comment]
No, Enclave bunker has been on the chopping block as a whole for a long time now.

**Review by printer16 — APPROVED** [review]

**Comment by ThyBaron** [comment]
Hello! The Enclave bunker has no discoverable intention for being in Yuma Valley. We will be removing it on these grounds for lore adherence.

**Comment by hecksadecimal** [comment]
@ThyBaron Don't forget, the VR aspect of this PR requires the specified config changes on the server that I can't accomplish through this PR.

**Pull request merged**
