### PR TITLE
Makes Booze O' Mat in bar have a density of 0

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## About The Pull Request

Title.

## Why It's Good For The Game

Sprites that are move a large distance generally create problems, as their collision box remains the same while the sprite is elsewhere, creating seemingly invisible walls. This makes it so that it can be walked through, but still able to be used.

### CODE REVIEW

**Comment by DeveloperLoser** [comment]
Not yet tested but what could possibly go wrong.

**Comment by DeveloperLoser** [comment]
Seems to be fine but my local is still fucked, loads Yuma and mapping subsystem fine so.

**Review by printer16 — COMMENTED** [review]
This seems like a band-aid solution and I'm not able to replicate it with other machines or the machine in question.

**Comment by Rohesie** [comment]
1) This is a map var-edit. If you want to change the properties of an object, do it in the object definition.
2) This is untested. What could possibly go wrong, you ask? This PR being closed, at the minimum.
3) It is not a long-distance movement issue, this is about the object being pixel-shifted. That means that it looks to be one tile in the east direction (`pixel_x = 32`) and one tile in the south (`pixel_y = -32`) from where it actually is. The solution for that is to remove the pixel shifting and re-aligning it in the map and, if the pixel shift is necessary, to rework the object to better handle where it can be accessed from (don't think this should be necessary).

**Comment by DeveloperLoser** [comment]
> 1. This is a map var-edit. If you want to change the properties of an object, do it in the object definition.

This would make Booze O' mat's as a whole have no collisions

> 2. This is untested. What could possibly go wrong, you ask? This PR being closed, at the minimum.

Not entirely, booted up server but my local gets stuck at loading the holodeck subsystem, still loads the Mapping 
subsystem however as well as Yuma, so no code errors or anything that could break the server

> 3. It is not a long-distance movement issue, this is about the object being pixel-shifted. That means that it looks to be one tile in the east direction (`pixel_x = 32`) and one tile in the south (`pixel_y = -32`) from where it actually is. The solution for that is to remove the pixel shifting and re-aligning it in the map and, if the pixel shift is necessary, to rework the object to better handle where it can be accessed from (don't think this should be necessary).

Whoever made the bar stuck the booze O' Mat inside an unreachable wall, so it could be re-mapped, but without the pixel                         
shift its impossible to interact with it without deconstructing a table and wall. Currently admins are just doing exactly what I've done here but I could just slightly remap it so the Booze O' Mat is placed in a normal spot, instead of inside a fucking wall.

**Comment by Mannybrado** [comment]
uhhh, i fixed it in #64

**Comment by DeveloperLoser** [comment]
Fixed

**Pull request closed without merging**
