### PR TITLE
Assault carbines re-chambered to 5mm, small amounts of 5mm have been delivered to yuma for testing

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

caravans have delivered small amounts of the once-popular 5mm round to yuma, although it is not yet widespread and not available for purchase
the assault carbines have been re-re-chambered back to 5mm, after all the originals had been changed to match the most pre-dominant round in the game, these are also only in small batches for testing purposes

the 5mm round was a pre-war round designed to cut through pre-war combat armor through sheer velocity, however it paid for this design feature with poor terminal ballistics
this was enough to sideline it for most of its use in the wastes due to armor being rare, but the strange abundance of armor in the wastes of yuma has led to renewed interest in it 

## Why It's Good For The Game

5.56 assault carbines were just assault rifles but better
5mm didnt exist in the game except for the now-removed minigun
future proofs the AK-112 and minigun if you ever want it back

this makes it a little different from existing 5.56 weapons
also, assault carbine is 5mm in the lore
will not have 0.5AP cancer, but instead halved to .25AP, substantially better than 7.62 but still not to the same insane degree as it was before, and low base damage makes it worse vs critters
box of 5mm rounds added, cannot be made, for testing purposes only due to place holder sprite, has 60rounds (to fill up two magazines with no leftover)
5mm comes in 30 round magazines, no variations

the assault carbine still will not spawn anywhere, so just dick around in the thunderdome to get a feel for who should have it

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: 5mm rifle round for rifles, .25 AP instead of .5AP
add: 5mm assault rifle magazine (30rds only)
add: 5mm box of ammo, 60rnds, uses 5.56 box as a placeholder, strictly for testing only
tweak: assault carbine is now chambered for 5mm
balance: assault carbine now fires a little faster
/:cl:

### CODE REVIEW

**Comment by cornercube** [comment]
@buffyuwu 
another one is stale

**Comment by buffyuwu** [comment]
@zuliouse what do you think

**Comment by zuliouse** [comment]
0.25 AP is pretty fucking strong, especially for a burst weapon. @chemistrymain3 thoughts?

**Comment by cornercube** [comment]
> 0.25 AP is pretty fucking strong, especially for a burst weapon. @chemistrymain3 thoughts?

.2 then?
that would put it on par with .308

**Pull request closed without merging**
