### PR TITLE
Quirk fixes + Removal of Bluespace Plant Mutation

### LINKED ISSUE #91: Remove the bluespace plant trait.
Teleporting plants is not good for a multitude of obvious reasons, and this trait is still accessible if plants are mutated. Removal would be appreciated.

### PR DESCRIPTION
**Pull request by mishulinya**
- Adds a extra point to Poor Aim (because you can't shoot in a straight line)
- Fixes Monophobia to be less retarded with a depression mood event
- Removes Phobia negative quirk due to it's retardness
- Moves Cannibal Quirk to neutral quirks

Closes #91

### CODE REVIEW

**Comment by Looreydev** [comment]
I'd once again love to remind there's a **Pull Request Temaplate** which you **shouldn't** Ctrl + A and deletebut rather fill out. Located [here](https://github.com/FortunaSS13/Fortuna/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and also in the PR description by default.

**Comment by mishulinya** [comment]
> 
> 
> I'd once again love to remind there's a **Pull Request Template** which you **shouldn't** Ctrl + A and delete but rather fill out. Located [here](https://github.com/FortunaSS13/Fortuna/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and also in the PR description by default.

Apologies, i'll try not to repeat my mistakes again.

**Comment by zuliouse** [comment]
Has this been tested locally?

**Comment by mishulinya** [comment]
> 
> 
> Has this been tested locally?

Yes. It works just fine from my part.

**Comment by mishulinya** [comment]
There's no errors or anything from what i have experienced. They work fine.

**Comment by BadAtThisGame302** [comment]
The dev for this left

**Pull request closed without merging**
