### PR TITLE
Updates progressbars

### PR DESCRIPTION
**Pull request by printer16**
## About The Pull Request
Updates progress bars to be more in-line with the current version of TG progressbars.

## Why It's Good For The Game
In the current state, progressbars is a bit outdated and responsible for a considerable amount of runtimes.

## Pre-Merge Checklist
- [X] Your Pull Request contains no breaking changes
- [X] You tested your changes locally, and they work.
- [X] There are no new Runtimes that appear.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by hecksadecimal** [comment]
This seems to be causing some strange behaviour. 
I've tested it locally, and when I try and weld scrap it's blinding me even though I have a welding helmet on.

**Comment by printer16** [comment]
> This seems to be causing some strange behaviour.
> I've tested it locally, and when I try and weld scrap it's blinding me even though I have a welding helmet on.

Will take a look at it tomorrow. I tested it with cutting down trees.

**Comment by printer16** [comment]
> This seems to be causing some strange behaviour.
> I've tested it locally, and when I try and weld scrap it's blinding me even though I have a welding helmet on.

I am unable to reproduce the mentioned bug. 
image

**Comment by hecksadecimal** [comment]
I'll test this again soon.

**Pull request merged**
