### PR TITLE
Raider change

### PR DESCRIPTION
**Pull request by printer16**
## About The Pull Request

This PR stops raiders from turning from simple_animals to human mobs. Also reorganizes the code a bit  (raider was defined 2 times!) and adds dead sprites for the mobs.

## Why It's Good For The Game

I have a suspicion that spawning a bunch of human carbon corpses which all process injuries, traumas, etc. is not a good idea when there's a significant amount of raiders on the map.  The side-effect of this is that raider corpses are no longer loot able nor can you harvest organs or the such, but that can be revisited if this is confirmed to be a cause of lag for the server late-game. 

## Pre-Merge Checklist
- [X] Your Pull Request contains no breaking changes
- [X] You tested your changes locally, and they work.
- [X] There are no new Runtimes that appear.
- [X] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by RagingLemons1** [comment]
I don't like this, some of the raiders drop some pretty good loot (bosses). Any way to tweak it so they drop stuff anyways?

**Comment by printer16** [comment]
> I don't like this, some of the raiders drop some pretty good loot (bosses). Any way to tweak it so they drop stuff anyways?

They still drop their weapon. I'm interested in having the PR test merged to see its effects before working on having them drop their armor/other stuff as well.

**Comment by dawsonkeyes** [comment]
Yes, but raiders such as the boss mobs drop raider-brand combat armor that’s generally really good

**Comment by printer16** [comment]
> Yes, but raiders such as the boss mobs drop raider-brand combat armor that’s generally really good, but it’s on their bodies. Maybe consider determining the difference through a test server first? Lay out 100
> corpses and check the master controller with and without them.
I understand your concern, but having it test merged for 1-2 rounds during high pop is my intention.

**Comment by hecksadecimal** [comment]
I'd like to see how this goes on the server too, so I'm merging this.

**Comment by whataboutism-alos** [comment]
okay, so, uhm, i actually made a github account specifically to comment on this pull request! the change made in this pr is a detraction to the player experience insofar as my time on the server since its merging goes.

it takes away my ability to have things to do. playing a legion auxilia, dead raiders are the *only* way for my character to get armors, cloaks, etc. to refurbish and upgrade for the legion faction’s other members. i cannot run dungeons while playing a legion auxilia character, should not be killing or robbing other characters for their armor, and a single set of armor dropping from a single boss is not viable for a faction that needs to have some semblance of fairness in who gets what armor, even if it’s all evenly a lower quality of protection.

because they’re simplemobs, it also takes away my ability to fireman-carry them to clean up, my ability to crucify them, and my ability to mix and spraypaint their clothes to make them look more similar to actual players to spook characters more authentically and provide a more atmospheric environment to the game. instead of setting up something like this: 
i have had to simply stick raiders all on one tile in a dark corner every time and hope no one notices they’re there. at this point i have found myself saying it would be better to have the raiders poof into thin air than leave these useless, carbon-copy, non-interactive blobs that we now have.

speaking to the pr’s good intentions, i haven’t noticed any noticeable decrease in lag (read: still the occasional spike) either on my end or in general playerbase perception, making the point of this, though high-minded and worth the time given thus far, ultimately moot!

**Pull request merged**
