### PR TITLE
Wayfarer Tribal Deletion (#2 Electric Boogaloo)

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Removal of the Wayfarer Tribe and all references to them. Replacement of the Tribe with 2 loadouts for Wastelander. Renaming of a lot of gear to generic tribal items. Removal of their village from the map.

## Why It's Good For The Game

The Wayfarer Tribe is a DR leftover, packed with horrendously cringe fan-fiction lore and awful stereotypes. Players of the faction are frequently LRP and often complained about, the Tribe has little to no governance or structure and is not regularly played. Replacement of the Tribe with Wastelander loadouts until someone creates a new Tribe without the caveman speak and cringe lore.

I have no expectation that this will be merged without proper discussion on the Discord, but I just wanted to get this over and done with so we could come to a decision.

## Pre-Merge Checklist
- [ ] Your Pull Request contains no breaking changes
- [ ] You tested your changes locally, and they work.
- [ ] There are no new Runtimes that appear.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Tribal wastelander loadouts, one technophobe, one regular
del: Wayfarer tribal roles, village
tweak: Renamed and set new paths for a lot of tribal gear.
/:cl:

### CODE REVIEW

**Comment by ThyBaron** [comment]
Hello! The Tribe is undergoing renovation both lore-wise and developmentally to peel them away from Wayfarer's and their... interesting history! I will be keeping this on hold until their writers give me the green or red light, which in this case - is likely the red, given their work hasn't even begun yet.

**Comment by Jaaackx** [comment]
@ThyBaron From discussion in #tribe-ooc and Zuli's comments, the tribal lorewriter is okay with these changes until the faction is reworked; all this will do is disable the slots, rename the gear and remove them from the map for the time being until a better alternative is designed.

We do however need to have a server survey/vote on this regardless, and the PR has map changes that need adding before it can come out of draft.

**Comment by Jaaackx** [comment]
whydafuq the checks still failing

**Comment by Jaaackx** [comment]
that's why

**Pull request closed without merging**
