### PR TITLE
Killa's donator stuff

### PR DESCRIPTION
**Pull request by PhoronRestructurantHuman**
## About The Pull Request
Killa's donator stuff

## Why It's Good For The Game
Becuause it's Killa's donator stuff

## Pre-Merge Checklist
- [ ]x Your Pull Request contains no breaking changes
- [ x] You tested your changes locally, and they work.
- [ ] There are no new Runtimes that appear.
- [ x] You documented all of your changes.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by zuliouse** [comment]
No weapons or armor in donor loadouts.

**Comment by dawsonkeyes** [comment]
Haw

**Comment by BadAtThisGame302** [comment]
Man was banned, don't think he gonna be using this anytime soon

**Comment by hecksadecimal** [comment]
Yep, they're gone now. 
Closing this.

**Pull request closed without merging**
