### PR TITLE
QoL and optimization

### PR DESCRIPTION
**Pull request by buffyuwu**
equipment loadout duffels will qdel when they have no items in them, removing the clutter of endless equipment duffels around the map. 

trying to optimize functions users spam by forcing them to stoplag after execution

more QoL but this time regarding the admin notifications about time of day changes

:cl:
add: prettier rain with atmospheric sound effects
tweak: various optimizations
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
https://streamable.com/1zfi4r

> loadout duffels that hold ur excess items now delete when they're empty
feat. new rain sounds and text 
its a much longer clip and not earrapey nor does it come in and out
it starts with thunder, eventually rain comes in, rain fades out after a bit and thats that
not 3 earrape rain clips lol
the rain doesnt stay the entire weather effect bc not everyone wants a free white noise generator but it lasts abooouuuuttt a minute

**Comment by Looreydev** [comment]
Just trying to understand here, is there any reason you're never using the Pull Request Template? ☹️
@buffyuwu

**Comment by Looreydev** [comment]
Besides that, on first glance this looks fine.

**Review by ThyBaron — APPROVED** [review]
Needed this!

**Pull request merged**
