### PR TITLE
[MDB IGNORE] Oasis Remake (done btw)

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Completely remakes Oasis. Take a look, give feedback in this PR and I'll change stuff.
oasis

## Why It's Good For The Game
Player housing. Also, it looks better.

## Changelog
:cl:
tweak: the entirety of oasis
del: old oasis
add: new oasis
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
edited the road to be less bland

**Comment by UntoldTactics** [comment]
ah shit, here we go again

**Comment by Mannybrado** [comment]
BTW, the eastern most wall has double reinforced walls for better security, if you're too lazy to look at mapdiffbot.

**Comment by cornercube** [comment]
color wise, it could use some blue/purple to contrast the brown/yellow
just so that it stands out from the wastes a bit more

the road is blueish, so that helps stand out against the sand, but the brown wood looks too much like the brown dirt outside

**Comment by Mannybrado** [comment]
I added in some vines around the place, as well as adding in some more and varying up the carpets so there's more color variety in some places.

**Comment by Mannybrado** [comment]
The shopkeeper's mansion was remade per request. I moved the prospectors to the east side of town, the matrix to the middle, and did this. 
image

**Comment by Mannybrado** [comment]
guh

**Comment by Mannybrado** [comment]
oasisdone
latest version by the way

**Comment by Mannybrado** [comment]
basically done unless anyone has more suggestions or any mistakes they can point out

**Comment by cornercube** [comment]
> basically done unless anyone has more suggestions or any mistakes they can point out
maybe just add a clothesmat and a balls/vim machine somewhere

**Comment by cornercube** [comment]
> The shopkeeper's mansion was remade per request. I moved the prospectors to the east side of town, the matrix to the middle, and did this.

minor thing: shopkeep probably does not need both a booze and soda fountain
you could replace them with a single booze o mat, which is still more alcohol than he will ever be able to finish but is still technically finite

**Comment by Mannybrado** [comment]
> minor thing: shopkeep probably does not need both a booze and soda fountain
> you could replace them with a single booze o mat, which is still more alcohol than he will ever be able to finish but is still technically finite

there's no reason to make it finite and i dont want to continue working on this any further

**Pull request merged**
