### PR TITLE
bigger irons, lore friendlier, and Oasis adjustments

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request

all police pistols in yuma have had their barrel's strengthened to take .357 rounds, enabling them to hit harder, after frequent complaints that all 6 shots could connect and do nothing
the classic .357 now properly represents its larger size over the police pistol and has the long barrel multiplier (-1 spread, +2 damage) at the cost of being single action (6 fire speed)
all loadouts with police pistols now spawn with .357 speedloaders, and the item spawner spawns it with a .357 next to it

oasis PD has encouraged citizens not to question why you cant stuff .38s into the police pistol anymore despite physically fitting in the chamber

after complaints by citizens that the provisioner loadout was taken solely for its gun, it is having its spare magazines reduced to just 1 extra mag
bums have also become craftier and upgraded their zip gun to a 5.56 pipe rifle, a single shot weapon with high damage
mayor has ~~embezzled~~ borrowed some funds from the coffers with help of their secretary, they both have ~400 caps to play with, although the mayor still has static spawn and so still comes out on top

totally unrelated to the above news, roving traders now have a random amount of cash between 80 and 240 instead of 350
it is believed to have been caused by a oversupply of roving traders and pressure from the hub to stop devaluing their currency

random gun spawn now spawns fewer T1 and T2 guns, since you can find the zipgun and pipe gun in trashpiles now

## Why It's Good For The Game

police pistol is chambered in .357 in dead money, its also way underpowered for a T5 spawn as a .38
the .357 in FNV was a single action weapon, its also a normal-sized weapon compared to the small-sized police pistol, so it should have a harder hitting projectile at the cost of slower shooting
the two guns now do different things despite sharing a projectile, and also sets a precedent for ammo bloat cut down

provisioners 10mm had 36 rounds of 29 damage each, for 1000+ total damage, lowering it to 1 spare mag will reduce it to about 600 damage worth of ammo, more in line with the rest of the town
bums zipgun is not unique enough now, so gets the  5.56 pipe rifle to make them a little more special
proper lady and detective have .357 ammo to fit their gun
by popular demand: lots of people requested a money boost to the civilian heads of oasis

T1 and T2 spawns have a lower weight, since all the weapons in that section are trashpile guns

random wastelanders do not deserve more money than most head roles
less disappointment for everyone now

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
add: oasis operating funds, a box with ~225 worth of currency inside
balance: citizen loadout changes
balance: police pistol much stronger
balance: .357 is now slower but stronger and more accurate
balance: trashpiles now spawn more from the middle of their tiers
balance: mayor has a medium cash pile changed to high, secretary has a box of operating funds
balance: roving trader loadout now only has 80-160 caps, instead of 350
/:cl:

### CODE REVIEW

**Comment by Wotzizname** [comment]
Fan the Hammer addition by any chance?

**Comment by cornercube** [comment]
> Fan the Hammer addition by any chance?
i am ~~ the ghost of time~~ a contributor, not the ghost of miracle wishes

not a bad idea though, I will pass it down the line

**Review by ThyBaron — APPROVED** [review]
Barony approved!

**Comment by cornercube** [comment]
darn, didnt mean to overrule the approval

**Review by ThyBaron — APPROVED** [review]
Good work!

**Pull request merged**
