### PR TITLE
does what i was told to do and reduces faction slots

### PR DESCRIPTION
**Pull request by ghost**
1 cent

1 vet decan

1 prime decan

2 vets

2 primes

3 recruits

1 forgemaster

2 explorer

slave and auxilla roles untouched

1 vexillarius

no recruit decanus

## Why It's Good For The Game

i was told to do it

## Pre-Merge Checklist
- [x] Your Pull Request contains no breaking changes
- [x] You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

## Changelog
:cl:
del: Fun
/:cl:

### CODE REVIEW

**Comment by zuliouse** [comment]
NB: Do not merge until other complementary changes are ready

**Comment by zuliouse** [comment]
> Please leave the Vex alone, Legion ins't the same without him.

vex isn't being touched, the PR description isn't up to date 
look at the code changes

**Comment by AdamElTablawy** [comment]
temp close

**Comment by Jawnner** [comment]
Think the Paladin Slayer should keep the M1919, as constantly repairing/upkeep on the AER12 wouldn't make much sense, even for the senior officer.

**Comment by AdamElTablawy** [comment]
> Think the Paladin Slayer should keep the M1919, as constantly repairing/upkeep on the AER12 wouldn't make much sense, even for the senior officer.

canonically the legion just grabs laser weapons and uses them till they break so i agree

i just can't figure out a decent weapon that would fit on a paladin-slayer because currently the m1919 is just 'best weapon' and that makes this 'best loadout'

**Comment by Jawnner** [comment]
> > Think the Paladin Slayer should keep the M1919, as constantly repairing/upkeep on the AER12 wouldn't make much sense, even for the senior officer.
> 
> canonically the legion just grabs laser weapons and uses them till they break so i agree
> 
> i just can't figure out a decent weapon that would fit on a paladin-slayer because currently the m1919 is just 'best weapon' and that makes this 'best loadout'

I like the M1919 because it fits the bill of the Paladin Slayer being more of a shock-trooper type loadout. A heavily armored brute advancing with a high caliber machinegun fits the bill pretty well.

I think if anything, Frontline Centurion could have a look at. While the 14mm is powerful, I don't know if it should be used as a primary weapon. The power fist added ontop of it makes it a loadout that was better when Legion speedboost was a thing. I was thinking of the assault carbine whenever that pr got merged, or even just making the 12.7/14mm smg a thing finally.

**Comment by AdamElTablawy** [comment]
> > > Think the Paladin Slayer should keep the M1919, as constantly repairing/upkeep on the AER12 wouldn't make much sense, even for the senior officer.
> > 
> > 
> > canonically the legion just grabs laser weapons and uses them till they break so i agree
> > i just can't figure out a decent weapon that would fit on a paladin-slayer because currently the m1919 is just 'best weapon' and that makes this 'best loadout'
> 
> I like the M1919 because it fits the bill of the Paladin Slayer being more of a shock-trooper type loadout. A heavily armored brute advancing with a high caliber machinegun fits the bill pretty well.
> 
> I think if anything, Frontline Centurion could have a look at. While the 14mm is powerful, I don't know if it should be used as a primary weapon. The power fist added ontop of it makes it a loadout that was better when Legion speedboost was a thing. I was thinking of the assault carbine whenever that pr got merged, or even just making the 12.7/14mm smg a thing finally.

i dont want to add any more burstfire weapons at this time because burstfire stinky and we don't have tgs full auto component yet

and the power fist, at the moment, does not work as intended

**Pull request closed without merging**
