### PR TITLE
legion loadout changes

### PR DESCRIPTION
**Pull request by carbous**
### About The Pull Request

Right so after discovering legion explorers starts with a brushgun, i went on to change that. I then tweaked a lot of the legion loadouts making some a little weaker and others a little stronger, overall making the legion weaker. (after some tweaks its kind of a legion buff to some degrees)
### Why It's Good For The Game
makes the explorers not completly busted and also fixes some issues brought on by legion players about recruit legion melee and vet legion melee

### Pre-Merge Checklist

- [x]  Your Pull Request contains no breaking changes
- [x]  You tested your changes locally, and they work.
- [x] There are no new Runtimes that appear.
- [x] You documented all of your changes.

**Changelog**
🆑balanced: the explorers snipers now get a sniper rifle instead of a brush gun, their night vision was also removed, their other loadout was changed from a lever action shotgun to a mp5 smg. recruits and prime legion doesnt get hard yard anymore, instead their melee loadout have a trekking book. legion recruits now get a fireaxe instead of a lance. legion prime frontliner now get a legion shield, a 10mm pistol and the trekking book. legion veterans berserker now get a legion lance instead of a fire axe. legion prime decanus now gets a 10mm smg instead of a grease gun. legion vet decanus now gets a super sledge instead of a fire axe and a grease gun instead of a carl gustav. vet decanus now gets a brush gun instead of a sks. vet now gets a 10mm smg instead of a sniper rifle. centurion has his 10mm smg replaced with a 14mm pistol. vex now gets a 10mm smg instead of s sniper rifle

### CODE REVIEW

**Comment by carbous** [comment]
issue where i cant see if the loadouts are ok in game because all loadouts, those i changed and every others, just open a white screen

**Comment by Mannybrado** [comment]
change the veteran's lance back to a fireaxe. its what they use in new vegas and thus in lore, also, the lance is pussy shit compared to the fireaxe.

**Comment by carbous** [comment]
fireaxe is completly useless and until melee is fixed, its just not a good thing to give them

**Comment by carbous** [comment]
alright the pr is ready

**Comment by Terguntreklar** [comment]
I don't believe you've fully documented your changes in the description, an example of this is the fact that you replaced the Vet Decan's SKS with a brush gun.
You ought to update your description.
Besides, many changes are just questionable, why remove the SKS entirely with an overused gun that's honestly too easy to find?
should this be merged, the SKS should be added to spawn lists in bunkers, adding more diversity, something which many balancing PRs don't take into account imo.

**Pull request merged**
