### PR TITLE
BoS Loadouts Update

### PR DESCRIPTION
**Pull request by Jawnner**
## About The Pull Request

Adds in new loadouts for Knights (Infiltrator/MP5SD), returns the R82 Heavy Service Rifle to the Defender loadouts and gets rid of the relatively weak Commando Carbine.

Gives Senior Paladin loadouts a proper sidearm now.

## Why It's Good For The Game

Senior Paladins wanted an actual sidearm, so Brotherhood quartermasters were able to get together and finally get around to issuing them a pistol depending on their main weapon.

Knights had a laughably weak ballistic option when it came to the commando carbine, so the R82 has been returned to them along with a new loadout option of the MP5SD, perfect for infiltration/night operations if they get around to doing it.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Sidearms to Senior Paladin loadouts
add: R82 path, MP5SD, new loadout Infiltrator
del: commando carbine path
/:cl:

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
The R82 is incredibly useless and also an NCR weapon.

Make them their own subtype weapon.

**Comment by Jawnner** [comment]
> The R82 is incredibly useless and also an NCR weapon.
> 
> Make them their own subtype weapon.
> 
> The MP5 is also very very good.

The R82 isn't in any NCR loadouts, or is it a blueprint spawn for their base or LO. I chose it because I didn't want to exactly give them a marksman, but the commando carbine is actually more useless than the R82.

**Comment by Jawnner** [comment]
> The R82 is incredibly useless and also an NCR weapon.
> 
> Make them their own subtype weapon.
> 
> The MP5 is also very very good.

Then maybe instead of an Infiltrator type deal, since it would either be an Uzi + Suppressor or the MP5SD, give them a shotgun loadout?  Or just scrap it entirely.

**Comment by Jawnner** [comment]
Going back to the drawing board a bit, have a good idea.

**Pull request closed without merging**
