### PR TITLE
Adds cosmetic stealth suit

### PR DESCRIPTION
**Pull request by dawsonkeyes**
This PR adds a cosmetic chinese stealth suit for a specific donator. This does not include proper custom loadout code (as that code is a mess from what I could see and I had issues adding the suit in that manner) but it does add the suit and helmet themselves. Simple as.

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
The files throwing errors weren't so much as touched why is this happening to meeee

**Comment by zuliouse** [comment]
What canonical reason would there be for a Chinese stealth suit to be in Yuma, AZ?

**Comment by dawsonkeyes** [comment]
> What canonical reason would there be for a Chinese stealth suit to be in Yuma, AZ?

The chinese were doing some wacky infiltration stuff, particularly around the vegas area (where yuma is near) and the donor's character is one of the operatives, ghoulified.

I don't write this shit, ok man? I'm just the coder

**Comment by Rohesie** [comment]
Did the lore peeps approve this?

**Comment by Looreydev** [comment]
> Did the lore peeps approve this?

@dawsonkeyes

**Comment by dawsonkeyes** [comment]
> > Did the lore peeps approve this?
> 
> @dawsonkeyes

I dunno. Again, I don’t write this stuff. Best to ping them in dev over it?

**Comment by Looreydev** [comment]
> I dunno. Again, I don’t write this stuff. Best to ping them in dev over it?

Lore people said you should make it clear that the suit is nonfunctional via flavor text and name.

**Comment by zuliouse** [comment]
Change the path to something generic please, no mention of donor anything.

**Comment by dawsonkeyes** [comment]
> Change the path to something generic please, no mention of donor anything.

All done

**Review by Looreydev — APPROVED** [review]
O-K.

**Pull request merged**
